import { handleCorsPreflightRequest } from '../_shared/corsHeaders.ts';
import { createCanonicalEvidenceClients,canonicalEvidenceErrorStatus } from '../_shared/canonicalEvidence/auth.ts';
import { createRequestContext,jsonResponse,logEvent } from '../_shared/requestContext.ts';
import { z } from 'zod';

const schema=z.object({attachment_id:z.string().uuid(),decision:z.enum(['accept','reassign','request_correction','not_relevant','mark_malicious']),request_id:z.string().uuid().nullable().optional(),reason_code:z.string().trim().min(3).max(100),notes:z.string().trim().min(3).max(5000)});
function safeName(value:string){return([...value.normalize('NFKC')].map(character=>{const code=character.charCodeAt(0);return code<=31||code===127||'/\\:*?"<>|'.includes(character)?'_':character;}).join('').replace(/^\.+/,'').slice(0,180)||'attachment');}

Deno.serve(async(req)=>{const context=createRequestContext(req);const preflight=handleCorsPreflightRequest(req);if(preflight)return preflight;if(req.method!=='POST')return jsonResponse(context,{error:'Method not allowed'},405,{Allow:'POST'});let copied:string|null=null;try{const parsed=schema.safeParse(await req.json());if(!parsed.success)return jsonResponse(context,{error:'Invalid request',details:parsed.error.flatten()},400);const {admin,client,user}=await createCanonicalEvidenceClients(req);const input=parsed.data;const {data:attachment,error}=await client.from('inbound_email_attachments').select('id,original_filename,quarantine_storage_path,review_status,message_id,inbound_email_messages(candidate_supplier_id),proposed_request_id').eq('id',input.attachment_id).single();if(error||!attachment)throw new Error('Attachment not found or inaccessible');if(attachment.review_status!=='pending')throw new Error('Attachment was already reviewed');let finalPath:string|null=null;if(input.decision==='accept'||input.decision==='reassign'){if(!input.request_id)throw new Error('Request is required for acceptance');const message=Array.isArray(attachment.inbound_email_messages)?attachment.inbound_email_messages[0]:attachment.inbound_email_messages;if(!message?.candidate_supplier_id||!attachment.quarantine_storage_path)throw new Error('Verified supplier and quarantine object are required');finalPath=`${message.candidate_supplier_id}/${input.request_id}/inbound/${attachment.id}/${safeName(attachment.original_filename)}`;const copy=await admin.storage.from('inbound-email-quarantine').copy(attachment.quarantine_storage_path,finalPath,{destinationBucket:'compliance-documents'});if(copy.error)throw copy.error;copied=finalPath;}const {data:result,error:reviewError}=await admin.rpc('review_inbound_attachment_v1',{p_actor_id:user.id,p_attachment_id:attachment.id,p_decision:input.decision,p_request_id:input.request_id??attachment.proposed_request_id??null,p_final_storage_path:finalPath,p_reason:input.reason_code,p_notes:input.notes});if(reviewError){if(copied)await admin.storage.from('compliance-documents').remove([copied]);throw reviewError;}logEvent('info','inbound_attachment_reviewed',context,{actor_id:user.id,attachment_id:attachment.id,decision:input.decision,reason_code:input.reason_code});return jsonResponse(context,result);}catch(error){logEvent('error','inbound_attachment_review_failed',context,{error:error instanceof Error?error.message:String(error)});return jsonResponse(context,{error:error instanceof Error?error.message:'Review failed'},canonicalEvidenceErrorStatus(error));}});
