/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect,useMemo,useState } from 'react';
import { AlertTriangle,CheckCircle2,Eye,Inbox,Loader2,RefreshCw,ShieldAlert,XCircle } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';

const correctionReasons=[['wrong_document_type','Wrong document type'],['missing_pages','Missing pages'],['unreadable','Unreadable'],['wrong_supplier','Wrong supplier'],['wrong_facility','Wrong facility'],['expired','Expired'],['scope_mismatch','Scope mismatch'],['signature_missing','Signature missing'],['other','Other']];
export function InboundEmailReviewQueue({buyerId}:{buyerId:string}){
  const client=supabase as any;const {toast}=useToast();const [messages,setMessages]=useState<any[]>([]);const [attachments,setAttachments]=useState<any[]>([]);const [requests,setRequests]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);const [selected,setSelected]=useState<Record<string,string>>({});const [notes,setNotes]=useState<Record<string,string>>({});const [reasonCodes,setReasonCodes]=useState<Record<string,string>>({});
  const load=async()=>{setLoading(true);try{const [{data:m,error:me},{data:r,error:re}]=await Promise.all([client.from('inbound_email_messages').select('*').eq('candidate_buyer_id',buyerId).in('status',['awaiting_review','quarantined','partially_accepted']).order('received_at',{ascending:false}),client.from('document_requests').select('id,title,supplier_id,status,document_type').eq('buyer_id',buyerId).in('status',['pending','rejected']).order('created_at',{ascending:false})]);if(me||re)throw me||re;const ids=(m||[]).map((x:any)=>x.id);let a:any[]=[];if(ids.length){const result=await client.from('inbound_email_attachments').select('*').in('message_id',ids).order('created_at');if(result.error)throw result.error;a=result.data||[];}setMessages(m||[]);setAttachments(a);setRequests(r||[]);}catch(error:any){toast({title:'Email intake unavailable',description:error.message||'Could not load inbound replies',variant:'destructive'});}finally{setLoading(false);}};
  // Loading is intentionally keyed to the active buyer; load is recreated by
  // render because it closes over the current client and toast implementation.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{void load();},[buyerId]);
  const grouped=useMemo(()=>new Map(messages.map(m=>[m.id,attachments.filter(a=>a.message_id===m.id)])),[messages,attachments]);
  const view=async(id:string)=>{setBusy(id);try{const {data,error}=await supabase.functions.invoke('get-inbound-attachment-url-v1',{body:{attachment_id:id}});if(error||!data?.signed_url)throw error||new Error('Preview unavailable');window.open(data.signed_url,'_blank','noopener,noreferrer');}catch(error:any){toast({title:'Preview unavailable',description:error.message,variant:'destructive'});}finally{setBusy(null);}};
  const decide=async(attachment:any,decision:string)=>{const requestId=selected[attachment.id]||attachment.proposed_request_id;const reasonCode=decision==='accept'||decision==='reassign'?'intake_verified':reasonCodes[attachment.id]||'';const reviewNotes=(notes[attachment.id]||'').trim();if(['accept','reassign','request_correction'].includes(decision)&&!requestId){toast({title:'Select a request',variant:'destructive'});return;}if(!reasonCode||reviewNotes.length<3){toast({title:'Reason and review notes are required',variant:'destructive'});return;}setBusy(attachment.id);try{const {error}=await supabase.functions.invoke('review-inbound-attachment-v1',{body:{attachment_id:attachment.id,decision,request_id:requestId||null,reason_code:reasonCode,notes:reviewNotes}});if(error)throw error;toast({title:decision==='request_correction'?'Correction requested':'Review recorded'});await load();}catch(error:any){toast({title:'Review failed',description:error.message,variant:'destructive'});}finally{setBusy(null);}};
  if(loading)return <div className="flex min-h-[320px] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin"/></div>;
  return <div className="space-y-5 p-6">
    <div className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Email Intake Review</h1><p className="text-sm text-muted-foreground">Items here need your judgment -- clearly matched, virus-free replies are already routed into your request queue.</p></div><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div>
    {!messages.length&&<Card><CardContent className="flex flex-col items-center gap-2 py-14"><Inbox className="h-9 w-9 text-muted-foreground"/><p className="font-medium">No email replies awaiting review</p></CardContent></Card>}
    {messages.map(message=><Card key={message.id} className={message.status==='quarantined'?'border-amber-300':''}><CardHeader><div className="flex items-start justify-between gap-4"><div><CardTitle className="text-base">{message.subject||'(No subject)'}</CardTitle><p className="mt-1 text-sm text-muted-foreground">From {message.normalized_sender} · {new Date(message.received_at).toLocaleString()}</p></div><Badge variant={message.status==='quarantined'?'destructive':'secondary'}>{message.status.replaceAll('_',' ')}</Badge></div></CardHeader><CardContent className="space-y-4">
      <div className="rounded-md bg-muted/50 p-3 text-sm"><div className="flex items-center gap-2">{message.match_result==='matched'?<CheckCircle2 className="h-4 w-4 text-emerald-600"/>:<ShieldAlert className="h-4 w-4 text-amber-600"/>}<span className="font-medium">{message.match_result}</span></div><p className="mt-1 text-muted-foreground">{(message.match_reasons||[]).join(', ')||message.quarantine_reason||'No deterministic match reason'}</p>{message.text_body&&<p className="mt-3 max-h-28 overflow-auto whitespace-pre-wrap border-t pt-3">{message.text_body.slice(0,2000)}</p>}</div>
      {(grouped.get(message.id)||[]).map((attachment:any)=>{const eligible=requests.filter(r=>r.supplier_id===message.candidate_supplier_id);return <div key={attachment.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">{attachment.original_filename}</p><p className="text-xs text-muted-foreground">{attachment.detected_mime_type||attachment.declared_mime_type||'unknown'} · {attachment.file_size?`${Math.ceil(attachment.file_size/1024)} KB`:'unknown size'} · scan {attachment.scan_status}</p></div><Button size="sm" variant="outline" disabled={!attachment.quarantine_storage_path||busy===attachment.id} onClick={()=>void view(attachment.id)}><Eye className="mr-2 h-4 w-4"/>Preview</Button></div>
        {attachment.classification?.method==='ai_shadow'&&<div className="mt-3 rounded-md border border-violet-200 bg-violet-50 p-2 text-xs text-violet-900">AI shadow suggestion: {attachment.classification.request_id||'no match'} · {Math.round(Number(attachment.classification.confidence||0)*100)}% · human review required</div>}
        {attachment.review_status==='pending'?<div className="mt-4 space-y-3"><div className="grid gap-3 md:grid-cols-2"><Select value={selected[attachment.id]||attachment.proposed_request_id||''} onValueChange={v=>setSelected(s=>({...s,[attachment.id]:v}))}><SelectTrigger><SelectValue placeholder="Select matching request"/></SelectTrigger><SelectContent>{eligible.map(r=><SelectItem key={r.id} value={r.id}>{r.title} · {r.document_type}</SelectItem>)}</SelectContent></Select><Select value={reasonCodes[attachment.id]||''} onValueChange={v=>setReasonCodes(s=>({...s,[attachment.id]:v}))}><SelectTrigger><SelectValue placeholder="Correction/rejection reason"/></SelectTrigger><SelectContent>{correctionReasons.map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><Textarea placeholder="Required review notes shown in the audit trail and correction message" value={notes[attachment.id]||''} onChange={e=>setNotes(s=>({...s,[attachment.id]:e.target.value}))}/><div className="flex flex-wrap gap-2"><Button size="sm" disabled={busy===attachment.id||attachment.scan_status!=='clean'} onClick={()=>void decide(attachment,selected[attachment.id]&&selected[attachment.id]!==attachment.proposed_request_id?'reassign':'accept')}><CheckCircle2 className="mr-1 h-4 w-4"/>Accept into request</Button><Button size="sm" variant="outline" disabled={busy===attachment.id} onClick={()=>void decide(attachment,'request_correction')}><XCircle className="mr-1 h-4 w-4"/>Request correction</Button><Button size="sm" variant="outline" disabled={busy===attachment.id} onClick={()=>void decide(attachment,'not_relevant')}>Not relevant</Button><Button size="sm" variant="destructive" disabled={busy===attachment.id} onClick={()=>void decide(attachment,'mark_malicious')}><AlertTriangle className="mr-1 h-4 w-4"/>Malicious</Button></div></div>:<div className="mt-3 flex gap-2"><Badge variant="outline">{attachment.review_status}</Badge>{attachment.review_reason_code&&<Badge variant="secondary">{attachment.review_reason_code}</Badge>}</div>}
      </div>;})}
    </CardContent></Card>)}
  </div>;
}
