-- Buyer AI summary: one current briefing per buyer, regenerated by the
-- buyer-ai-summary edge function on a 2-hourly cron.
--
-- input_fingerprint is the cost control: the function hashes the buyer's
-- computed facts and skips the model call entirely when the hash is unchanged,
-- so quiet accounts cost a query rather than a completion. generated_at is the
-- last real generation; checked_at is the last cron pass either way.

CREATE TABLE IF NOT EXISTS public.buyer_ai_summaries (
  buyer_id uuid PRIMARY KEY REFERENCES public.buyers(id) ON DELETE CASCADE,
  bullets jsonb NOT NULL DEFAULT '[]'::jsonb,
  follow_ups jsonb NOT NULL DEFAULT '[]'::jsonb,
  input_fingerprint text,
  model text,
  generated_at timestamptz,
  checked_at timestamptz NOT NULL DEFAULT now(),
  error text
);

COMMENT ON TABLE public.buyer_ai_summaries IS
  'Current AI-generated compliance briefing per buyer. Bullets are LLM-worded but every number is computed server-side and validated against the fact set before storage.';

CREATE INDEX IF NOT EXISTS buyer_ai_summaries_checked_at_idx
  ON public.buyer_ai_summaries (checked_at DESC);

GRANT SELECT ON public.buyer_ai_summaries TO authenticated;
GRANT ALL ON public.buyer_ai_summaries TO service_role;
ALTER TABLE public.buyer_ai_summaries ENABLE ROW LEVEL SECURITY;

-- Read-only for members of the buyer org; writes go through the edge function
-- on the service role.
DROP POLICY IF EXISTS "Buyers read own AI summary" ON public.buyer_ai_summaries;
CREATE POLICY "Buyers read own AI summary" ON public.buyer_ai_summaries
  FOR SELECT TO authenticated USING (
    buyer_id IN (SELECT public.get_user_buyer_ids())
    OR public.is_admin(auth.uid())
  );

-- Schedule: every 2 hours on the hour. Same pg_net + vault-secret pattern as
-- the other scheduled processors. Idempotent.
SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname = 'buyer-ai-summary-2h';

SELECT cron.schedule(
  'buyer-ai-summary-2h',
  '0 */2 * * *',
  $$
  SELECT net.http_post(
    url := 'https://edwerzutsknhuplidhsj.supabase.co/functions/v1/buyer-ai-summary',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'X-System-Secret', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'system_cron_invocation')
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 300000
  ) AS request_id;
  $$
);
